market:
  front_addr: 180.168.146.187:10131
  broker_id: "9999"
  investor_id: "123456"
  password: 'password'
  flow_path: flow
  is_using_udp: false
  is_multicast: false

trade:
  front_addr: 180.168.146.187:10131
  broker_id: "9999"
  investor_id: "123456"
  password: 'password'
  flow_path: flow
  is_using_udp: false
  is_multicast: false


